In [46]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [47]:
df = pd.read_csv("/Users/kkutumba/Downloads/insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance, test_size=0.2, random_state=25)

In [49]:
len(X_train)

22

In [50]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age']/100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age']/100


In [51]:
X_train_scaled

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.46              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

In [52]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

In [53]:
model.compile(optimizer='adam',
            loss='binary_crossentropy',
            metrics=['accuracy'])
model.fit(X_train_scaled, y_train, epochs=5000)


Epoch 1/5000
1/1 [==============================] - 0s 108ms/step - loss: 0.7113 - accuracy: 0.5000
Epoch 2/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.7110 - accuracy: 0.5000
Epoch 3/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.7106 - accuracy: 0.5000
Epoch 4/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.7102 - accuracy: 0.5000
Epoch 5/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.7098 - accuracy: 0.5000
Epoch 6/5000
1/1 [==============================] - 0s 997us/step - loss: 0.7094 - accuracy: 0.5000
Epoch 7/5000
1/1 [==============================] - 0s 994us/step - loss: 0.7091 - accuracy: 0.5000
Epoch 8/5000
1/1 [==============================] - 0s 959us/step - loss: 0.7087 - accuracy: 0.5000
Epoch 9/5000
1/1 [==============================] - 0s 922us/step - loss: 0.7083 - accuracy: 0.5000
Epoch 10/5000
1/1 [==============================] - 0s 931us/step - loss: 0.7079 - accuracy: 0.5000
Epoch 1

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



1/1 [==============================] - 0s 716us/step - loss: 0.5534 - accuracy: 0.6818
Epoch 1988/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.5533 - accuracy: 0.6818
Epoch 1989/5000
1/1 [==============================] - 0s 975us/step - loss: 0.5533 - accuracy: 0.6818
Epoch 1990/5000
1/1 [==============================] - 0s 955us/step - loss: 0.5532 - accuracy: 0.6818
Epoch 1991/5000
1/1 [==============================] - 0s 926us/step - loss: 0.5532 - accuracy: 0.6818
Epoch 1992/5000
1/1 [==============================] - 0s 925us/step - loss: 0.5532 - accuracy: 0.6818
Epoch 1993/5000
1/1 [==============================] - 0s 760us/step - loss: 0.5531 - accuracy: 0.6818
Epoch 1994/5000
1/1 [==============================] - 0s 974us/step - loss: 0.5531 - accuracy: 0.6818
Epoch 1995/5000
1/1 [==============================] - 0s 919us/step - loss: 0.5530 - accuracy: 0.6818
Epoch 1996/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.5530 - accurac

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



Epoch 3981/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.4854 - accuracy: 0.9091
Epoch 3982/5000
1/1 [==============================] - 0s 956us/step - loss: 0.4854 - accuracy: 0.9091
Epoch 3983/5000
1/1 [==============================] - 0s 881us/step - loss: 0.4854 - accuracy: 0.9091
Epoch 3984/5000
1/1 [==============================] - 0s 897us/step - loss: 0.4854 - accuracy: 0.9091
Epoch 3985/5000
1/1 [==============================] - 0s 939us/step - loss: 0.4853 - accuracy: 0.9091
Epoch 3986/5000
1/1 [==============================] - 0s 803us/step - loss: 0.4853 - accuracy: 0.9091
Epoch 3987/5000
1/1 [==============================] - 0s 986us/step - loss: 0.4853 - accuracy: 0.9091
Epoch 3988/5000
1/1 [==============================] - 0s 861us/step - loss: 0.4853 - accuracy: 0.9091
Epoch 3989/5000
1/1 [==============================] - 0s 816us/step - loss: 0.4852 - accuracy: 0.9091
Epoch 3990/5000
1/1 [==============================] - 0s 1ms/step - loss: 

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [54]:
model.evaluate(X_test_scaled, y_test)

1/1 [==============================] - 0s 32ms/step - loss: 0.3550 - accuracy: 1.0000


[0.35497748851776123, 1.0]

In [55]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 12ms/step


array([[0.70548487],
       [0.35569552],
       [0.16827849],
       [0.47801173],
       [0.7260697 ],
       [0.82949835]], dtype=float32)

In [56]:
X_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [57]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [58]:
coef, intercept = model.get_weights()
coef, intercept

(array([[5.060867 ],
        [1.4086502]], dtype=float32),
 array([-2.9137027], dtype=float32))

In [59]:
def sigmoid(x):
    import math
    return 1/(1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [60]:
def prediction_function(age, affordability):
    weighted_sum = coef[0]*age + coef[1]*affordability +intercept
    return sigmoid(weighted_sum)

In [61]:
prediction_function(.47,1)

0.7054848693136117

In [62]:
prediction_function(.18,1)

0.35569549781937626

In [63]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [64]:
def sigmoid_numpy(X):
    return 1/(1+np.exp(-X))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [65]:
def gradient_descent(age, affordability, y_true, epochs,loss_threshold):
    w1=w2=1
    bias=0
    rate=0.2
    n=len(age)

    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)

        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))
        bias_d = np.mean(y_predicted-y_true)

        w1=w1-rate*w1d
        w2=w2-rate*w2d
        bias=bias-rate*bias_d

        print(f'epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_threshold:
            break
    return w1, w2, bias
        
        

In [66]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,1000,0.4631)

epoch:0, w1:0.9899630533880708, w2:0.9793392501578115, bias:-0.04536747094547433, loss:0.7113403233723417
epoch:1, w1:0.9808337546778705, w2:0.9601041841396611, bias:-0.08844836034422315, loss:0.6987651063954486
epoch:2, w1:0.972586839169299, w2:0.942266485877647, bias:-0.1293107283551011, loss:0.6875433297120104
epoch:3, w1:0.9651936232070926, w2:0.9257903732405255, bias:-0.16803049568697329, loss:0.6775595931706438
epoch:4, w1:0.9586226466228289, w2:0.9106337166009422, bias:-0.2046898438716404, loss:0.6687008225711776
epoch:5, w1:0.9528403065718678, w2:0.896749186215355, bias:-0.23937565604595784, loss:0.6608579550375189
epoch:6, w1:0.9478114621207347, w2:0.8840853813262782, bias:-0.2721780454775931, loss:0.6539272567425941
epoch:7, w1:0.9434999939520945, w2:0.8725879034764842, bias:-0.3031890066205157, loss:0.6478112814378953
epoch:8, w1:0.9398693085467643, w2:0.8622003465747071, bias:-0.33250121137114796, loss:0.6424194972136492
epoch:9, w1:0.936882780768951, w2:0.8528651857990085,

(5.0408587547689505, 1.4566062542254667, -2.9551717266626407)

In [67]:
coef, intercept

(array([[5.060867 ],
        [1.4086502]], dtype=float32),
 array([-2.9137027], dtype=float32))